version: '3.8'

services:
  # MySQL Database
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: TESLA
      MYSQL_USER: tesla
      MYSQL_PASSWORD: tesla1234
    ports:
      - "3307:3306"  # External port 3307, internal port 3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro  # Auto-run SQL on startup

  # Flask Web App (Backend + Frontend)
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - "7700:7700"
    environment:
      - DOCKER_ENV=true  # Set the flag for config logic
    depends_on:
      - db

volumes:
  mysql_data: